typography_spectrum: 0.4068895138334483
color:
  brandStrength: 0.2195662846788764
  lightness: 0.7555900181178004
  saturation: 0.25284305098466575
  rhythmicContrast: 0.8794435632880777
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.9171026451513171
author:
  name: ''
  email: ''
  url: ''
name: Notebook of a New Writer
title: Striving to achieve my personal goals while helping others
