typography_spectrum: 0.4068895138334483
color:
  brandStrength: 0.9475104424636811
  lightness: 0.8036976051516831
  saturation: 0.8937592529691756
  rhythmicContrast: 0.5886286695022136
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
layout_spectrum: 0.7365493553224951
author:
  name: Troy Salisbury
  email: mtroys@msn.com
  url: 'http://www.tsalisbury.com'
name: TSalisbury
title: Notebook of a New Writer
